const intro=document.querySelector('#intro'),stage=document.querySelector('#stage'),card=document.querySelector('#wishCard'),btn=document.querySelector('#wishBtn');
setTimeout(()=>{stage.classList.add('show')},700);setTimeout(()=>intro.classList.add('hide'),2800);
const lanterns=document.querySelector('.lanterns'),petals=document.querySelector('.petals');
for(let i=0;i<16;i++){let e=document.createElement('i');e.className='lantern';e.style.left=(4+Math.random()*92)+'vw';e.style.bottom=(-20-Math.random()*40)+'vh';e.style.transform=`scale(${.55+Math.random()*.8})`;e.style.animationDuration=(10+Math.random()*12)+'s';e.style.animationDelay=(4+Math.random()*10)+'s';lanterns.appendChild(e)}
for(let i=0;i<30;i++){let e=document.createElement('i');e.className='petal';e.style.left=Math.random()*100+'vw';e.style.top=(-10-Math.random()*40)+'vh';e.style.animationDuration=(8+Math.random()*11)+'s';e.style.animationDelay=(3+Math.random()*14)+'s';petals.appendChild(e)}
btn.addEventListener('click',()=>{card.classList.toggle('open');burst(innerWidth*.62,innerHeight*.52,90)});
const c=document.querySelector('#fx'),x=c.getContext('2d');let W,H,dpr=Math.min(devicePixelRatio,2),stars=[],mouse={x:-999,y:-999};function resize(){W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;c.style.width=W+'px';c.style.height=H+'px';x.setTransform(dpr,0,0,dpr,0,0)}resize();addEventListener('resize',resize);addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;if(Math.random()>.65)stars.push({x:e.clientX,y:e.clientY,vx:(Math.random()-.5)*.35,vy:-.3-Math.random()*.7,a:1,r:1+Math.random()*2,l:80})});
function burst(px,py,n){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=.5+Math.random()*2.5;stars.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,a:1,r:1+Math.random()*2.2,l:80+Math.random()*50})}}
function tick(){x.clearRect(0,0,W,H);for(let i=stars.length-1;i>=0;i--){let p=stars[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.004;p.a-=1/p.l;if(p.a<=0){stars.splice(i,1);continue}x.beginPath();x.arc(p.x,p.y,p.r*p.a,0,Math.PI*2);x.fillStyle=`rgba(255,236,184,${p.a})`;x.shadowBlur=12;x.shadowColor='#ffd58b';x.fill()}requestAnimationFrame(tick)}tick();
setTimeout(()=>burst(W*.68,H*.31,75),4100);
