from playwright.sync_api import sync_playwright, expect
from pathlib import Path
import json, os
from PIL import Image
OUT = Path('output/qa')
OUT.mkdir(parents=True, exist_ok=True)
EXE = os.environ.get('BROWSER_PATH', r'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe')
URL = os.environ.get('TEST_URL', 'http://127.0.0.1:8000/')
checks, errors, network = [], [], []
def ok(name): checks.append(name)
def watch(page):
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.on('response', lambda response: network.append({'url':response.url,'status':response.status}) if response.status >= 400 else None)
def moon_location(page):
    return page.evaluate('''() => {
      const img=document.querySelector('#sceneImage'), b=img.getBoundingClientRect(), h=document.querySelector('#home').getBoundingClientRect();
      const s=Math.max(b.width/img.naturalWidth,b.height/img.naturalHeight);
      const pos=getComputedStyle(img).objectPosition.split(' ').map(n=>parseFloat(n)/100);
      return {x:b.left-h.left+(b.width-img.naturalWidth*s)*pos[0]+img.naturalWidth*s*.665,y:b.top-h.top+(b.height-img.naturalHeight*s)*pos[1]+img.naturalHeight*s*.255};
    }''')
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=EXE,headless=True)
    context=browser.new_context(viewport={'width':1440,'height':960},accept_downloads=True)
    page=context.new_page(); watch(page)
    page.goto(URL,wait_until='networkidle'); page.locator('#skipBtn').click(); page.wait_for_timeout(100)
    assert not page.locator('.hero').evaluate("e=>e.classList.contains('is-entering')")
    assert page.locator('img[src]').evaluate_all('imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0)')
    ok('Intro completes and every local image decodes')
    page.locator('#moonHotspot').click()
    expect(page.locator('.moon-ring')).to_have_count(1)
    actual=page.locator('.moon-ring').evaluate('e=>({x:parseFloat(e.style.left),y:parseFloat(e.style.top)})')
    expected=moon_location(page)
    assert abs(actual['x']-expected['x'])<5 and abs(actual['y']-expected['y'])<5, (actual,expected)
    ok('Moon ripple matches the rendered image coordinates')
    page.locator('[data-mood=osmanthus]').click()
    expect(page.locator('body')).to_have_attribute('data-mood','osmanthus')
    page.locator('[data-mood=lantern]').click()
    assert page.locator('.sky-lantern').count()>=6
    page.locator('[data-mood=moon]').click()
    expect(page.locator('.sky-lantern')).to_have_count(0)
    ok('Mood switching starts and clears the corresponding effects')
    page.locator('.hero-actions [data-open-wish]').click()
    expect(page.locator('#wishDialog')).to_be_visible()
    page.locator('[data-wish]').first.click()
    expect(page.locator('#wishInput')).to_have_value('愿所念之人，岁岁平安。')
    page.locator('#wishInput').fill('愿爸爸妈妈平安喜乐，岁岁常相见。')
    page.locator('#wishBtn').click()
    expect(page.locator('#wishDialog')).not_to_be_visible()
    expect(page.locator('.sky-lantern.personal span')).to_have_text('愿爸爸妈妈平安喜乐，岁岁常相见。')
    page.wait_for_timeout(1600); page.screenshot(path=str(OUT/'wish-in-flight.png'))
    page.reload(wait_until='networkidle'); page.locator('#skipBtn').click(); page.wait_for_timeout(100)
    page.locator('.hero-actions [data-open-wish]').click()
    expect(page.locator('#wishCount')).to_contain_text('1 盏心灯')
    expect(page.locator('#wishHistoryList')).to_contain_text('愿爸爸妈妈平安喜乐')
    page.keyboard.press('Escape')
    expect(page.locator('#wishDialog')).not_to_be_visible()
    ok('Custom wishes launch, persist through reload, and modal closes with Escape')
    page.locator('#nextPoem').click(); page.wait_for_timeout(300)
    expect(page.locator('#poemText')).to_contain_text('海上生明月')
    page.locator('#savePoem').click()
    expect(page.locator('#savePoem')).to_have_attribute('aria-pressed','true')
    page.locator('#letterRitual').click()
    expect(page.locator('#letterTab')).to_have_attribute('aria-selected','true')
    page.locator('#usePoem').click()
    expect(page.locator('#letterInput')).to_have_value('海上生明月，天涯共此时。')
    page.locator('#recipientInput').fill('远方的你')
    page.locator('#senderInput').fill('柚子')
    page.locator('#letterInput').fill('愿你一路有星光相伴，所行皆坦途，所念皆如愿。中秋快乐！')
    page.locator('#previewLetter').click()
    expect(page.locator('#cardPreview')).to_be_visible()
    page.screenshot(path=str(OUT/'card-dialog.png'))
    with page.expect_download() as info: page.locator('#downloadCard').click()
    download=info.value; download.save_as(str(OUT/'sample-card.png'))
    assert Image.open(OUT/'sample-card.png').size==(1080,1620)
    page.locator('#editLetter').click()
    expect(page.locator('#letterInput')).to_have_value('愿你一路有星光相伴，所行皆坦途，所念皆如愿。中秋快乐！')
    ok('Poetry selection, favorite, card editing, 1080×1620 PNG preview and download')
    page.locator('#lanternTab').focus(); page.keyboard.press('ArrowRight')
    expect(page.locator('#letterTab')).to_be_focused()
    page.keyboard.press('Home'); expect(page.locator('#lanternTab')).to_be_focused()
    page.keyboard.press('Escape')
    page.locator('#home').scroll_into_view_if_needed(); page.locator('#immerseBtn').click()
    expect(page.locator('body')).to_have_class('immersed')
    assert page.locator('.hero-inner').evaluate('e=>e.inert')
    page.keyboard.press('Escape'); assert not page.locator('.hero-inner').evaluate('e=>e.inert')
    expect(page.locator('#immerseBtn')).to_be_focused()
    ok('Keyboard tabs, modal focus, immersive mode and Escape restoration')
    page.locator('#soundBtn').click(); expect(page.locator('#soundBtn')).to_have_attribute('aria-pressed','true')
    page.locator('#soundBtn').click(); expect(page.locator('#soundBtn')).to_have_attribute('aria-pressed','false')
    page.locator('#replayBtn').click(); expect(page.locator('.hero')).to_have_class('hero is-entering')
    page.locator('#skipBtn').click(); expect(page.locator('.hero')).to_have_class('hero')
    ok('User-activated sound, replay and skip')
    page.screenshot(path=str(OUT/'desktop-hero.png'))
    for sel in ['#moments','#poetry','.closing']:
        page.locator(sel).scroll_into_view_if_needed(); page.wait_for_timeout(950)
    page.screenshot(path=str(OUT/'desktop-full.png'),full_page=True)
    for w,h in [(320,740),(390,844),(768,1024),(1024,768),(1920,1080)]:
        page.set_viewport_size({'width':w,'height':h}); page.locator('#home').scroll_into_view_if_needed(); page.wait_for_timeout(200)
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth'),f'overflow at {w}'
        page.locator('#moonHotspot').click()
        actual=page.locator('.moon-ring').last.evaluate('e=>({x:parseFloat(e.style.left),y:parseFloat(e.style.top)})')
        expected=moon_location(page)
        assert abs(actual['x']-expected['x'])<5 and abs(actual['y']-expected['y'])<5,(w,actual,expected)
        page.wait_for_timeout(600)
    ok('No overflow and accurate moon effects at 320, 390, 768, 1024 and 1920 pixels')
    mobile=browser.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True)
    mp=mobile.new_page(); watch(mp); mp.goto(URL,wait_until='networkidle'); mp.locator('#skipBtn').click(); mp.wait_for_timeout(100)
    mp.screenshot(path=str(OUT/'mobile-hero.png'))
    for sel in ['#moments','#poetry','.closing']:
        mp.locator(sel).scroll_into_view_if_needed(); mp.wait_for_timeout(950)
    mp.screenshot(path=str(OUT/'mobile-full.png'),full_page=True)
    mp.locator('#letterRitual').click(); mp.locator('#recipientInput').fill('家人'); mp.locator('#previewLetter').click()
    expect(mp.locator('#cardPreview')).to_be_visible(); mp.screenshot(path=str(OUT/'mobile-card-dialog.png'))
    assert mp.locator('#wishDialog').evaluate('e=>e.scrollWidth<=e.clientWidth')
    ok('Mobile card preview fits dialog width')
    reduced=browser.new_context(viewport={'width':390,'height':844},reduced_motion='reduce')
    rp=reduced.new_page(); watch(rp); rp.goto(URL,wait_until='networkidle')
    expect(rp.locator('.hero')).to_have_class('hero')
    rp.locator('#moonHotspot').click(); expect(rp.locator('.moon-ring')).to_have_count(0)
    rp.locator('.hero-actions [data-open-wish]').click(); rp.locator('#wishBtn').click()
    expect(rp.locator('.sky-lantern.personal')).to_have_count(1)
    assert rp.locator('.sky-lantern.personal').evaluate('e=>getComputedStyle(e).animationName')=='none'
    ok('Reduced motion skips intro and provides a stationary wish light')
    restricted=browser.new_context(viewport={'width':390,'height':844},reduced_motion='reduce')
    restricted.add_init_script("Object.defineProperty(window,'localStorage',{get(){throw new Error('Storage unavailable')}})")
    sp=restricted.new_page(); watch(sp); sp.goto(URL,wait_until='networkidle')
    sp.locator('.hero-actions [data-open-wish]').click(); sp.locator('#wishInput').fill('<img src=x onerror=alert(1)>'); sp.locator('#wishBtn').click()
    expect(sp.locator('.sky-lantern.personal span')).to_have_text('<img src=x onerror=alert(1)>')
    assert sp.locator('img[src=x]').count()==0
    ok('Unavailable storage and HTML-like wish text are handled safely')
    assert not errors,errors
    assert not network,network
    report={'passed':len(checks),'checks':checks,'runtimeErrors':errors,'failedResponses':network}
    (OUT/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
    print(json.dumps(report,ensure_ascii=False,indent=2))
    browser.close()

